shell zsh
shell_integration no-cursor

font_family monospace
font_size 11

window_padding_width 6

background_opacity 0.50

# Keybinds
clear_all_shortcuts true
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+enter new_window
map ctrl+shift+w close_window
map ctrl+tab next_window
map ctrl+shift+tab previous_window
